events {}

http {
  upstream user_service {
    server user-service:80;
  }

  upstream product_service {
    server product-service:8000;
  }

  upstream order_service {
    server order-service:8000;
  }

  server {
    listen 80;

    location /users/ {
      proxy_pass http://user_service;
    }

    location /products/ {
      proxy_pass http://product_service;
    }

    location /orders/ {
      proxy_pass http://order_service;
    }
  }
}
